export enum GameType {
  COUNTRY_QUIZ = 'COUNTRY_QUIZ',
  GUESS_WORD = 'GUESS_WORD',
  MYSTERY_CUISINE = 'MYSTERY_CUISINE',
  MUSIC = 'MUSIC',
  WORLD_MAP = 'WORLD_MAP',
  MIME = 'MIME',
  DUEL = 'DUEL',
  CULTURE_CODE = 'CULTURE_CODE',
  HISTORY_CLASH = 'HISTORY_CLASH',
}

export enum GameStatus {
  WAITING = 'WAITING',
  READY = 'READY',
  COUNTDOWN = 'COUNTDOWN',
  PLAYING = 'PLAYING',
  ROUND_COMPLETE = 'ROUND_COMPLETE',
  NEXT_ROUND = 'NEXT_ROUND',
  FINISHED = 'FINISHED',
  RESULTS = 'RESULTS',
  CANCELLED = 'CANCELLED',
  ABANDONED = 'ABANDONED',
}

export enum GameMode {
  SOLO = 'SOLO',
  FRIEND = 'FRIEND',
  RANDOM = 'RANDOM',
  DUEL = 'DUEL',
}

export enum PassportStatus {
  LOCKED = 'LOCKED',
  DISCOVERED = 'DISCOVERED',
  COMPLETED = 'COMPLETED',
  MASTERED = 'MASTERED',
}

export enum ConversationType {
  DIRECT = 'DIRECT',
  GAME_ROOM = 'GAME_ROOM',
}

export enum NotificationType {
  GAME_INVITE = 'GAME_INVITE',
  GAME_STARTED = 'GAME_STARTED',
  GAME_RESULT = 'GAME_RESULT',
  NEW_MESSAGE = 'NEW_MESSAGE',
  BADGE_UNLOCKED = 'BADGE_UNLOCKED',
  COUNTRY_UNLOCKED = 'COUNTRY_UNLOCKED',
  LEVEL_UP = 'LEVEL_UP',
  SYSTEM = 'SYSTEM',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  REVIEWED = 'REVIEWED',
  DISMISSED = 'DISMISSED',
  ACTIONED = 'ACTIONED',
}

export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
}
